### ISSUE TITLE
todo(features): Write a decent task-list

### ISSUE THREAD

**Issue by iamclaytonray** [iamclaytonray/graphql-cms#1]
The main goal of GraphQL CMS is to manage data from a GUI without letting users access interfaces, enums, types, directives, and so on. This is great for companies that want Content Administrators to CRUD content without exposing internal APIs. Basically, a high quality WordPress but on GraphQL and React. **(Preact? Reason?)**

- [ ] CMS inherits types & fields from the API. Endpoints can be changed if user is authorized.
- [ ] Deployment options through the CMS. (Up, Now, others?)
- [ ] Authorize root/admin users to access interfaces, enums, types, etc.
- [ ] Allow root/admin users to CRUD Directives and Scalars.
